services:
  db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    profiles:
    - fullstack
  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "5050:80"
    profiles:
    - fullstack
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    volumes:
      - .:/workspace:cached
    ports:
      - "8000:8000"
    tty: true
    env_file:
      - .env
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    depends_on:
      - db
    profiles:
    - fullstack
  frontend:
    depends_on:
      - backend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    volumes:
      - .:/workspace:cached
      - /workspace/frontend/node_modules
    ports:
      - "3000:3000"
    tty: true
    profiles:
      - fullstack

volumes:
  db-data:
