# Generated by Django 5.0.6 on 2024-07-09 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=10)),
                (
                    "amenities",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("dw", "Dishwasher"),
                            ("ld", "Laundry"),
                            ("os", "Outdoor Space"),
                            ("ev", "Elevator"),
                            ("gr", "Garage"),
                            ("fp", "Fireplace"),
                            ("ac", "Central Air"),
                            ("ht", "Heater"),
                        ],
                    ),
                ),
                ("bedrooms", models.SmallIntegerField(default=0)),
                ("bathrooms", models.SmallIntegerField(default=0)),
                ("square_footage", models.IntegerField(default=0)),
                (
                    "building",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="buildings.building",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
    ]
