# Generated by Django 5.0.6 on 2024-06-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField()),
                ("description", models.TextField(blank=True, default="")),
                ("address", models.CharField(default="")),
                ("city", models.CharField(default="")),
                ("state", models.CharField(default="")),
                ("zipcode", models.PositiveIntegerField(default=0)),
                ("units", models.PositiveSmallIntegerField(default=0)),
                ("stories", models.PositiveSmallIntegerField(default=0)),
                ("year_built", models.IntegerField(default=0)),
            ],
        ),
    ]
