# Generated by Django 5.0.6 on 2024-07-09 02:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Listing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("date_available", models.DateField(blank=True)),
                (
                    "status",
                    models.SmallIntegerField(
                        choices=[
                            (0, "Off Market"),
                            (1, "Active"),
                            (2, "In Contract"),
                            (3, "Rented"),
                        ],
                        default=0,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
            ],
        ),
    ]
